#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    #line 2 "..\..\Views\SchemeEditor\Index.cshtml"
    using UsersDiosna.Sheme.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/SchemeEditor/Index.cshtml")]
    public partial class _Views_SchemeEditor_Index_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Sheme.Models.SchemeEditor>
    {
        public _Views_SchemeEditor_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\SchemeEditor\Index.cshtml"
  
    ViewBag.Title = "Scheme editor";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Scheme Editor</h4>\r\n");

            
            #line 8 "..\..\Views\SchemeEditor\Index.cshtml"
 using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    foreach (DynValue val in Model.SchemeTags)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteAttribute("href", Tuple.Create(" href=\"", 426), Tuple.Create("\"", 441)
, Tuple.Create(Tuple.Create("", 433), Tuple.Create("#", 433), true)
            
            #line 13 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 434), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 434), false)
);

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n            Dynamic value of tag: ");

            
            #line 14 "..\..\Views\SchemeEditor\Index.cshtml"
                             Write(val.column);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n");

            
            #line 16 "..\..\Views\SchemeEditor\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"collapse\"");

WriteAttribute("id", Tuple.Create(" id=\"", 559), Tuple.Create("\"", 571)
            
            #line 17 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 564), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 564), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-block\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Table:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 775), Tuple.Create("\"", 799)
, Tuple.Create(Tuple.Create("", 782), Tuple.Create("tableEdit_", 782), true)
            
            #line 20 "..\..\Views\SchemeEditor\Index.cshtml"
                                                    , Tuple.Create(Tuple.Create("", 792), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 792), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 800), Tuple.Create("\"", 818)
            
            #line 20 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 808), Tuple.Create<System.Object, System.Int32>(val.table
            
            #line default
            #line hidden
, 808), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Column:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 940), Tuple.Create("\"", 965)
, Tuple.Create(Tuple.Create("", 947), Tuple.Create("columnEdit_", 947), true)
            
            #line 21 "..\..\Views\SchemeEditor\Index.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 958), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 958), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 966), Tuple.Create("\"", 985)
            
            #line 21 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                       , Tuple.Create(Tuple.Create("", 974), Tuple.Create<System.Object, System.Int32>(val.column
            
            #line default
            #line hidden
, 974), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Ratio:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1106), Tuple.Create("\"", 1130)
, Tuple.Create(Tuple.Create("", 1113), Tuple.Create("ratioEdit_", 1113), true)
            
            #line 22 "..\..\Views\SchemeEditor\Index.cshtml"
                                                    , Tuple.Create(Tuple.Create("", 1123), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 1123), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1131), Tuple.Create("\"", 1149)
            
            #line 22 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 1139), Tuple.Create<System.Object, System.Int32>(val.ratio
            
            #line default
            #line hidden
, 1139), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Offset:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1271), Tuple.Create("\"", 1296)
, Tuple.Create(Tuple.Create("", 1278), Tuple.Create("offsetEdit_", 1278), true)
            
            #line 23 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 1289), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 1289), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1297), Tuple.Create("\"", 1316)
            
            #line 23 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                      , Tuple.Create(Tuple.Create("", 1305), Tuple.Create<System.Object, System.Int32>(val.offset
            
            #line default
            #line hidden
, 1305), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Unit:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1  form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1436), Tuple.Create("\"", 1459)
, Tuple.Create(Tuple.Create("", 1443), Tuple.Create("unitEdit_", 1443), true)
            
            #line 24 "..\..\Views\SchemeEditor\Index.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 1452), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 1452), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1460), Tuple.Create("\"", 1477)
            
            #line 24 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                  , Tuple.Create(Tuple.Create("", 1468), Tuple.Create<System.Object, System.Int32>(val.unit
            
            #line default
            #line hidden
, 1468), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Text color:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1603), Tuple.Create("\"", 1631)
, Tuple.Create(Tuple.Create("", 1610), Tuple.Create("textColorEdit_", 1610), true)
            
            #line 25 "..\..\Views\SchemeEditor\Index.cshtml"
                                                             , Tuple.Create(Tuple.Create("", 1624), Tuple.Create<System.Object, System.Int32>(val.id
            
            #line default
            #line hidden
, 1624), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1632), Tuple.Create("\"", 1654)
            
            #line 25 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                             , Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(val.textColor
            
            #line default
            #line hidden
, 1640), false)
);

WriteLiteral(" />\r\n                    <br />\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n");

            
            #line 30 "..\..\Views\SchemeEditor\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" href=\"#addDynVal\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n        Add new dynamic value\r\n    </a>\r\n");

            
            #line 34 "..\..\Views\SchemeEditor\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" id=\"addDynVal\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"card card-block\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Table:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1 form-control input-xs\"");

WriteLiteral(" name=\"tableNew\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Column:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteLiteral(" name=\"columnNew\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Ratio:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteLiteral(" name=\"ratioNew\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Offset:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteLiteral(" name=\"offsetNew\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Unit:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1  form-control input-xs\"");

WriteLiteral(" name=\"unitNew\"");

WriteLiteral(" />\r\n                <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Text color:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteLiteral(" name=\"textColorNew\"");

WriteLiteral(" />\r\n                <br />\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 48 "..\..\Views\SchemeEditor\Index.cshtml"

    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\SchemeEditor\Index.cshtml"
Write(Html.Raw(File.ReadAllText(Server.MapPath(Model.relativePath))));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                   
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\SchemeEditor\Index.cshtml"
      
    foreach (AgeBar ageBar in Model.SchemeAgeBars)
    {
        var tagAge = Model.BindingTags.First(p => p.id == ageBar.id || p.name == ageBar.id);

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteAttribute("href", Tuple.Create(" href=\"", 3356), Tuple.Create("\"", 3374)
, Tuple.Create(Tuple.Create("", 3363), Tuple.Create("#", 3363), true)
            
            #line 59 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3364), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 3364), false)
);

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n            Age Bar from tag:  ");

            
            #line 60 "..\..\Views\SchemeEditor\Index.cshtml"
                          Write(tagAge.columnName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n");

            
            #line 62 "..\..\Views\SchemeEditor\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"collapse\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3496), Tuple.Create("\"", 3511)
            
            #line 63 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3501), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 3501), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-block\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Table:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 3715), Tuple.Create("\"", 3742)
, Tuple.Create(Tuple.Create("", 3722), Tuple.Create("tableEdit_", 3722), true)
            
            #line 66 "..\..\Views\SchemeEditor\Index.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 3732), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 3732), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 3743), Tuple.Create("\"", 3771)
            
            #line 66 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                         , Tuple.Create(Tuple.Create("", 3754), Tuple.Create<System.Object, System.Int32>(tagAge.tableName
            
            #line default
            #line hidden
, 3754), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Column:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 3893), Tuple.Create("\"", 3921)
, Tuple.Create(Tuple.Create("", 3900), Tuple.Create("columnEdit_", 3900), true)
            
            #line 67 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 3911), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 3911), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 3922), Tuple.Create("\"", 3951)
            
            #line 67 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                            , Tuple.Create(Tuple.Create("", 3933), Tuple.Create<System.Object, System.Int32>(tagAge.columnName
            
            #line default
            #line hidden
, 3933), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Max. Age:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4075), Tuple.Create("\"", 4102)
, Tuple.Create(Tuple.Create("", 4082), Tuple.Create("ratioEdit_", 4082), true)
            
            #line 68 "..\..\Views\SchemeEditor\Index.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 4092), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 4092), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 4103), Tuple.Create("\"", 4128)
            
            #line 68 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                             , Tuple.Create(Tuple.Create("", 4114), Tuple.Create<System.Object, System.Int32>(ageBar.maxAge
            
            #line default
            #line hidden
, 4114), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">First color:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4255), Tuple.Create("\"", 4283)
, Tuple.Create(Tuple.Create("", 4262), Tuple.Create("offsetEdit_", 4262), true)
            
            #line 69 "..\..\Views\SchemeEditor\Index.cshtml"
                                                           , Tuple.Create(Tuple.Create("", 4273), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 4273), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 4284), Tuple.Create("\"", 4313)
            
            #line 69 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 4295), Tuple.Create<System.Object, System.Int32>(ageBar.firstColor
            
            #line default
            #line hidden
, 4295), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Second limit:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4441), Tuple.Create("\"", 4469)
, Tuple.Create(Tuple.Create("", 4448), Tuple.Create("offsetEdit_", 4448), true)
            
            #line 70 "..\..\Views\SchemeEditor\Index.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 4459), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 4459), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 4470), Tuple.Create("\"", 4499)
            
            #line 70 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 4481), Tuple.Create<System.Object, System.Int32>(ageBar.firstLimit
            
            #line default
            #line hidden
, 4481), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Second color:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4627), Tuple.Create("\"", 4655)
, Tuple.Create(Tuple.Create("", 4634), Tuple.Create("offsetEdit_", 4634), true)
            
            #line 71 "..\..\Views\SchemeEditor\Index.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 4645), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 4645), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 4656), Tuple.Create("\"", 4686)
            
            #line 71 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 4667), Tuple.Create<System.Object, System.Int32>(ageBar.secondColor
            
            #line default
            #line hidden
, 4667), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Third limit:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4813), Tuple.Create("\"", 4841)
, Tuple.Create(Tuple.Create("", 4820), Tuple.Create("offsetEdit_", 4820), true)
            
            #line 72 "..\..\Views\SchemeEditor\Index.cshtml"
                                                           , Tuple.Create(Tuple.Create("", 4831), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 4831), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 4842), Tuple.Create("\"", 4869)
            
            #line 72 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 4853), Tuple.Create<System.Object, System.Int32>(ageBar.secLimit
            
            #line default
            #line hidden
, 4853), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Third color:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4996), Tuple.Create("\"", 5024)
, Tuple.Create(Tuple.Create("", 5003), Tuple.Create("offsetEdit_", 5003), true)
            
            #line 73 "..\..\Views\SchemeEditor\Index.cshtml"
                                                           , Tuple.Create(Tuple.Create("", 5014), Tuple.Create<System.Object, System.Int32>(ageBar.id
            
            #line default
            #line hidden
, 5014), false)
);

WriteAttribute("ageBarue", Tuple.Create(" ageBarue=\"", 5025), Tuple.Create("\"", 5054)
            
            #line 73 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                 , Tuple.Create(Tuple.Create("", 5036), Tuple.Create<System.Object, System.Int32>(ageBar.thirdColor
            
            #line default
            #line hidden
, 5036), false)
);

WriteLiteral(" />\r\n                    <br />\r\n                </div>\r\n            </div>\r\n    " +
"    </div>\r\n");

            
            #line 78 "..\..\Views\SchemeEditor\Index.cshtml"
}

foreach (Graphiclist graphicList in Model.SchemeGraphicsList)
{
        var tag = Model.BindingTags.First(p => p.id == graphicList.id || p.name == graphicList.name);

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteAttribute("href", Tuple.Create(" href=\"", 5386), Tuple.Create("\"", 5409)
, Tuple.Create(Tuple.Create("", 5393), Tuple.Create("#", 5393), true)
            
            #line 83 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5394), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 5394), false)
);

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n            GraphicList for tag:  ");

            
            #line 84 "..\..\Views\SchemeEditor\Index.cshtml"
                             Write(tag.columnName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n");

            
            #line 86 "..\..\Views\SchemeEditor\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"collapse\"");

WriteAttribute("id", Tuple.Create(" id=\"", 5531), Tuple.Create("\"", 5551)
            
            #line 87 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5536), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 5536), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-block\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Table:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 5755), Tuple.Create("\"", 5787)
, Tuple.Create(Tuple.Create("", 5762), Tuple.Create("tableEdit_", 5762), true)
            
            #line 90 "..\..\Views\SchemeEditor\Index.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 5772), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 5772), false)
);

WriteAttribute("graphicListue", Tuple.Create(" graphicListue=\"", 5788), Tuple.Create("\"", 5818)
            
            #line 90 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                   , Tuple.Create(Tuple.Create("", 5804), Tuple.Create<System.Object, System.Int32>(tag.tableName
            
            #line default
            #line hidden
, 5804), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Column:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 5940), Tuple.Create("\"", 5973)
, Tuple.Create(Tuple.Create("", 5947), Tuple.Create("columnEdit_", 5947), true)
            
            #line 91 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 5958), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 5958), false)
);

WriteAttribute("graphicListue", Tuple.Create(" graphicListue=\"", 5974), Tuple.Create("\"", 6005)
            
            #line 91 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                      , Tuple.Create(Tuple.Create("", 5990), Tuple.Create<System.Object, System.Int32>(tag.columnName
            
            #line default
            #line hidden
, 5990), false)
);

WriteLiteral(" />\r\n");

            
            #line 92 "..\..\Views\SchemeEditor\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\SchemeEditor\Index.cshtml"
                     for (int i = 0; i < graphicList.items.Count; i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Index:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6225), Tuple.Create("\"", 6257)
, Tuple.Create(Tuple.Create("", 6232), Tuple.Create("indexEdit_", 6232), true)
            
            #line 94 "..\..\Views\SchemeEditor\Index.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 6242), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 6242), false)
);

WriteAttribute("graphicListue", Tuple.Create(" graphicListue=\"", 6258), Tuple.Create("\"", 6301)
            
            #line 94 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                        , Tuple.Create(Tuple.Create("", 6274), Tuple.Create<System.Object, System.Int32>(graphicList.items[i].index
            
            #line default
            #line hidden
, 6274), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Path:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6425), Tuple.Create("\"", 6456)
, Tuple.Create(Tuple.Create("", 6432), Tuple.Create("pathEdit_", 6432), true)
            
            #line 95 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 6441), Tuple.Create<System.Object, System.Int32>(graphicList.id
            
            #line default
            #line hidden
, 6441), false)
);

WriteAttribute("graphicListue", Tuple.Create(" graphicListue=\"", 6457), Tuple.Create("\"", 6499)
            
            #line 95 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                      , Tuple.Create(Tuple.Create("", 6473), Tuple.Create<System.Object, System.Int32>(graphicList.items[i].path
            
            #line default
            #line hidden
, 6473), false)
);

WriteLiteral(" />\r\n");

            
            #line 96 "..\..\Views\SchemeEditor\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <br />\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n");

            
            #line 101 "..\..\Views\SchemeEditor\Index.cshtml"
    }

    foreach (Textlist textList in Model.SchemeTextlist)
    {
            var tagText = Model.BindingTags.First(p => p.id == textList.id || p.name == textList.name );

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn btn-primary btn-xs\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6859), Tuple.Create("\"", 6879)
, Tuple.Create(Tuple.Create("", 6866), Tuple.Create("#", 6866), true)
            
            #line 106 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 6867), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 6867), false)
);

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n            TextList binded on tag: ");

            
            #line 107 "..\..\Views\SchemeEditor\Index.cshtml"
                               Write(tagText.columnName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </a>\r\n");

            
            #line 109 "..\..\Views\SchemeEditor\Index.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"collapse\"");

WriteAttribute("id", Tuple.Create(" id=\"", 7007), Tuple.Create("\"", 7024)
            
            #line 110 "..\..\Views\SchemeEditor\Index.cshtml"
, Tuple.Create(Tuple.Create("", 7012), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 7012), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card card-block\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Table:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7228), Tuple.Create("\"", 7257)
, Tuple.Create(Tuple.Create("", 7235), Tuple.Create("tableEdit_", 7235), true)
            
            #line 113 "..\..\Views\SchemeEditor\Index.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 7245), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 7245), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 7258), Tuple.Create("\"", 7289)
            
            #line 113 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                             , Tuple.Create(Tuple.Create("", 7271), Tuple.Create<System.Object, System.Int32>(tagText.tableName
            
            #line default
            #line hidden
, 7271), false)
);

WriteLiteral(" />\r\n                    <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Column:</span> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7411), Tuple.Create("\"", 7441)
, Tuple.Create(Tuple.Create("", 7418), Tuple.Create("columnEdit_", 7418), true)
            
            #line 114 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 7429), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 7429), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 7442), Tuple.Create("\"", 7473)
            
            #line 114 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                , Tuple.Create(Tuple.Create("", 7455), Tuple.Create<System.Object, System.Int32>(tagText.tableName
            
            #line default
            #line hidden
, 7455), false)
);

WriteLiteral(" />\r\n");

            
            #line 115 "..\..\Views\SchemeEditor\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 115 "..\..\Views\SchemeEditor\Index.cshtml"
                     for (int i = 0; i < textList.items.Count; i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Index:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7690), Tuple.Create("\"", 7719)
, Tuple.Create(Tuple.Create("", 7697), Tuple.Create("indexEdit_", 7697), true)
            
            #line 117 "..\..\Views\SchemeEditor\Index.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 7707), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 7707), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 7720), Tuple.Create("\"", 7757)
            
            #line 117 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 7733), Tuple.Create<System.Object, System.Int32>(textList.items[i].index
            
            #line default
            #line hidden
, 7733), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Path:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7881), Tuple.Create("\"", 7909)
, Tuple.Create(Tuple.Create("", 7888), Tuple.Create("pathEdit_", 7888), true)
            
            #line 118 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 7897), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 7897), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 7910), Tuple.Create("\"", 7947)
            
            #line 118 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                , Tuple.Create(Tuple.Create("", 7923), Tuple.Create<System.Object, System.Int32>(textList.items[i].value
            
            #line default
            #line hidden
, 7923), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Path:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 8071), Tuple.Create("\"", 8099)
, Tuple.Create(Tuple.Create("", 8078), Tuple.Create("pathEdit_", 8078), true)
            
            #line 119 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 8087), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 8087), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 8100), Tuple.Create("\"", 8141)
            
            #line 119 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                , Tuple.Create(Tuple.Create("", 8113), Tuple.Create<System.Object, System.Int32>(textList.items[i].textColor
            
            #line default
            #line hidden
, 8113), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                        <span");

WriteLiteral(" class=\"col-sm-1\"");

WriteLiteral(">Path:</span> ");

WriteLiteral("<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\" col-sm-1 form-control input-xs\"");

WriteAttribute("name", Tuple.Create(" name=\"", 8265), Tuple.Create("\"", 8293)
, Tuple.Create(Tuple.Create("", 8272), Tuple.Create("pathEdit_", 8272), true)
            
            #line 120 "..\..\Views\SchemeEditor\Index.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 8281), Tuple.Create<System.Object, System.Int32>(textList.id
            
            #line default
            #line hidden
, 8281), false)
);

WriteAttribute("textListue", Tuple.Create(" textListue=\"", 8294), Tuple.Create("\"", 8333)
            
            #line 120 "..\..\Views\SchemeEditor\Index.cshtml"
                                                                                , Tuple.Create(Tuple.Create("", 8307), Tuple.Create<System.Object, System.Int32>(textList.items[i].bgColor
            
            #line default
            #line hidden
, 8307), false)
);

WriteLiteral(" />\r\n");

            
            #line 121 "..\..\Views\SchemeEditor\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <br />\r\n                </div>\r\n            </div>\r\n        <" +
"/div>\r\n");

            
            #line 126 "..\..\Views\SchemeEditor\Index.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
