#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CMS/EditArticle.cshtml")]
    public partial class _Views_CMS_EditArticle_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.CMS.Models.ArticleModel>
    {
        public _Views_CMS_EditArticle_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("head", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 3 "..\..\Views\CMS\EditArticle.cshtml"
Write(Styles.Render("~/Content/summernote"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

            
            #line 5 "..\..\Views\CMS\EditArticle.cshtml"
  
    ViewBag.Title = "EditArticle";
    string selectedItem = " ";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Edit Article</h2>\r\n\r\n");

            
            #line 12 "..\..\Views\CMS\EditArticle.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\CMS\EditArticle.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\CMS\EditArticle.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n        <hr />\r\n");

WriteLiteral("        ");

            
            #line 18 "..\..\Views\CMS\EditArticle.cshtml"
   Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 20 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.bakeryId, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.DropDownListFor(model => model.bakeryId, Model.Ids, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.bakeryId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.Header, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 30 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.EditorFor(model => model.Header, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.Header, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 36 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control", @rows = 5 } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 39 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 52 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.HoursSpend, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.EditorFor(model => model.HoursSpend, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.HoursSpend, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.Attachment, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 62 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.EditorFor(model => model.Attachment, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 63 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.Attachment, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 68 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 70 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 71 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 76 "..\..\Views\CMS\EditArticle.cshtml"
       Write(Html.LabelFor(model => model.SectionId, htmlAttributes: new { @class = "control-label  col-lg-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"col-lg-9\"");

WriteLiteral(">\r\n");

            
            #line 78 "..\..\Views\CMS\EditArticle.cshtml"
                
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\CMS\EditArticle.cshtml"
                 if (Model.Sections.Exists(p => p.Selected == true))
                {
                    selectedItem = Model.Sections.First(p => p.Selected == true).Text;
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 82 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.DropDownListFor(model => model.SectionId, new SelectList(Model.Sections), selectedItem, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 83 "..\..\Views\CMS\EditArticle.cshtml"
           Write(Html.ValidationMessageFor(model => model.SectionId, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-lg-offset-2 col-lg-3\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 93 "..\..\Views\CMS\EditArticle.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 96 "..\..\Views\CMS\EditArticle.cshtml"
Write(Html.ActionLink("Back to List", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 99 "..\..\Views\CMS\EditArticle.cshtml"
Write(Scripts.Render("~/bundle/summernote",
                            "~/Scripts/CreateArticle.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("  ");

        }
    }
}
#pragma warning restore 1591
