#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    #line 2 "..\..\Views\CMS\Index.cshtml"
    using UsersDiosna.Handlers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CMS/Index.cshtml")]
    public partial class _Views_CMS_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<UsersDiosna.Models.Article>>
    {
        public _Views_CMS_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\CMS\Index.cshtml"
  
    ViewBag.Title = "List of Articles";
    string lastSectionName = "";
    string fileName = "";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h3>List of articles for this bakery</h3>\r\n");

            
            #line 10 "..\..\Views\CMS\Index.cshtml"
 if (User.IsInRole("CMS"))
{

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\CMS\Index.cshtml"
   Write(Html.ActionLink("Create new Section", "CreateSection", new { }, new { @class = "btn btn-xs btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");

WriteLiteral("    <p>\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Views\CMS\Index.cshtml"
   Write(Html.ActionLink("Create new Article", "CreateArticle", new { }, new { @class = "btn btn-xs btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");

WriteLiteral("    <p>\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\CMS\Index.cshtml"
   Write(Html.ActionLink("List of sections", "Sections", new { }, new { @class = "btn btn-xs btn-primary" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");

            
            #line 21 "..\..\Views\CMS\Index.cshtml"
}

            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\CMS\Index.cshtml"
                                                                                                                           

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\CMS\Index.cshtml"
 if (Model != null) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table table-condensed table-bordered table-hover table-responsive\"");

WriteLiteral(@">
            <tr>
                <th>
                    Created
                </th>
                <th>
                    Aut.
                </th>
                <th>
                    Subj.
                </th>
                <th>
                    Content
                </th>
                <th>
                    Costs
                </th>
                <th>
                    Hs.
                </th>
                <th>
                    Attachment
                </th>
                <th>
                    Attachment description
                </th>
                <th></th>
            </tr>
");

            
            #line 53 "..\..\Views\CMS\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\CMS\Index.cshtml"
             foreach (var item in Model)
            {
                if (item.Section.Name != lastSectionName)
                {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n");

            
            #line 58 "..\..\Views\CMS\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\CMS\Index.cshtml"
                       
                        lastSectionName = item.Section.Name;
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n                    <td><h5>");

            
            #line 61 "..\..\Views\CMS\Index.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Section.Name));

            
            #line default
            #line hidden
WriteLiteral("</h5></td>\r\n                </tr>\r\n");

            
            #line 63 "..\..\Views\CMS\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <tr");

WriteLiteral(" class=\"small\"");

WriteLiteral(">\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 66 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.DateTime.ToString(), 40, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 69 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.DisplayFor(modelItem => item.Author));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 72 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.Header, 40, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 75 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.Text, 15, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 78 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.Amount, 10, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 81 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.HoursSpend.ToString(), 10, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");

            
            #line 84 "..\..\Views\CMS\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\CMS\Index.cshtml"
                          if (item.Attachment != null)
                            {
                                fileName = item.Attachment;
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3242), Tuple.Create("\"", 3265)
            
            #line 89 "..\..\Views\CMS\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3249), Tuple.Create<System.Object, System.Int32>(item.Attachment
            
            #line default
            #line hidden
, 3249), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 3266), Tuple.Create("\"", 3315)
, Tuple.Create(Tuple.Create("", 3274), Tuple.Create("/Download/downloadFile?nameFile=", 3274), true)
            
            #line 89 "..\..\Views\CMS\Index.cshtml"
          , Tuple.Create(Tuple.Create("", 3306), Tuple.Create<System.Object, System.Int32>(fileName
            
            #line default
            #line hidden
, 3306), false)
);

WriteLiteral(">Download</a>\r\n                    </td>\r\n                    <td>\r\n");

WriteLiteral("                        ");

            
            #line 92 "..\..\Views\CMS\Index.cshtml"
                   Write(Html.Raw(CMSHandler.maxLength(item.Description, 150, "/CMS/DetailArticle/" + item.Id)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                        <s" +
"pan> ");

            
            #line 95 "..\..\Views\CMS\Index.cshtml"
                          Write(Html.ActionLink("Edit", "EditArticle", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 96 "..\..\Views\CMS\Index.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\CMS\Index.cshtml"
                         if (User.IsInRole("CMS"))
                        {


            
            #line default
            #line hidden
WriteLiteral("                            <span> | ");

            
            #line 99 "..\..\Views\CMS\Index.cshtml"
                                Write(Html.ActionLink("Details", "DetailArticle", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |</span>\r\n");

WriteLiteral("                            <span>");

            
            #line 100 "..\..\Views\CMS\Index.cshtml"
                             Write(Html.ActionLink("Delete", "DeleteArticle", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 101 "..\..\Views\CMS\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 104 "..\..\Views\CMS\Index.cshtml"
             }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n");

            
            #line 107 "..\..\Views\CMS\Index.cshtml"
}
else {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-offset-3\"");

WriteLiteral(">\r\n       <h4><b>No articles to this bakery has been found</b></h4>\r\n    </div>\r\n" +
"");

            
            #line 112 "..\..\Views\CMS\Index.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
