#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CMS/Sections.cshtml")]
    public partial class _Views_CMS_Sections_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<UsersDiosna.DBML.Section>>
    {
        public _Views_CMS_Sections_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\CMS\Sections.cshtml"
  
    ViewBag.Title = "Sections";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Sections</h2>\r\n<p>\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\CMS\Sections.cshtml"
Write(Html.ActionLink("Create New Section", "CreateSection"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"searchSections\"");

WriteLiteral(" onkeyup=\"filterSection()\"");

WriteLiteral(" placeholder=\"search for sections\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\CMS\Sections.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-condensed table-bordered table-hover table-responsive\"");

WriteLiteral(">\r\n        <tr>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayNameFor(model => model.ArticleId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayNameFor(model => model.Role));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th>\r\n");

WriteLiteral("                ");

            
            #line 29 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayNameFor(model => model.BakeryId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </th>\r\n            <th></th>\r\n        </tr>\r\n\r\n");

            
            #line 34 "..\..\Views\CMS\Sections.cshtml"
    
            
            #line default
            #line hidden
            
            #line 34 "..\..\Views\CMS\Sections.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 41 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayFor(modelItem => item.ArticleId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayFor(modelItem => item.Role));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.DisplayFor(modelItem => item.BakeryId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.ActionLink("Edit", "EditSection", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.ActionLink("Details", "DetailSection", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("                ");

            
            #line 55 "..\..\Views\CMS\Sections.cshtml"
           Write(Html.ActionLink("Delete", "DeleteSection", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n");

            
            #line 58 "..\..\Views\CMS\Sections.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    </table>\r\n");

            
            #line 61 "..\..\Views\CMS\Sections.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"col-md-offset-3\"");

WriteLiteral(">\r\n        <h4><b>No sections to this bakery has been found</b></h4>\r\n    </div>\r" +
"\n");

            
            #line 67 "..\..\Views\CMS\Sections.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
