#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Report\calender.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Report\calender.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    #line 3 "..\..\Views\Report\calender.cshtml"
    using UsersDiosna.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/calender.cshtml")]
    public partial class _Views_Report_calender_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Report.Models.DataReportModel>
    {
        public _Views_Report_calender_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Report\calender.cshtml"
  
    ViewBag.Title = "calender";
    string name = string.Empty;
    int EndType = 0;
    int amntTotal = 0;
    int amntOverall= 0;
    int amnt = 0;
    bool colourRow;
    int count = 0;
    int countOverall = 0;
    int year = ViewBag.year;
    int monthLess = ViewBag.Month - 1;
    int monthMore = ViewBag.Month + 1;
    if (monthLess < 1) {
        year--;
        monthLess = 12;
    }
    if (monthMore > 12) {
        year++;
        monthMore = 1;
    }
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    DateTime monthDT = new DateTime(year, ViewBag.month, 1);
    string monthName = monthDT.ToString("MMMM");


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Calender</h4>\r\n<div");

WriteLiteral(" class=\" col-md-10\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 896), Tuple.Create("\"", 933)
, Tuple.Create(Tuple.Create("", 903), Tuple.Create("/Report/Month/", 903), true)
            
            #line 35 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 917), Tuple.Create<System.Object, System.Int32>(monthLess
            
            #line default
            #line hidden
, 917), false)
, Tuple.Create(Tuple.Create("", 927), Tuple.Create("/", 927), true)
            
            #line 35 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 928), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 928), false)
);

WriteLiteral(">-1 month</a> Month: ");

            
            #line 35 "..\..\Views\Report\calender.cshtml"
                                                                                       Write(monthName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 35 "..\..\Views\Report\calender.cshtml"
                                                                                                  Write(year);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1001), Tuple.Create("\"", 1038)
, Tuple.Create(Tuple.Create("", 1008), Tuple.Create("/Report/Month/", 1008), true)
            
            #line 35 "..\..\Views\Report\calender.cshtml"
                                                                               , Tuple.Create(Tuple.Create("", 1022), Tuple.Create<System.Object, System.Int32>(monthMore
            
            #line default
            #line hidden
, 1022), false)
, Tuple.Create(Tuple.Create("", 1032), Tuple.Create("/", 1032), true)
            
            #line 35 "..\..\Views\Report\calender.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 1033), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 1033), false)
);

WriteLiteral(">+1 month</a>\r\n    <p></p>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table-bordered table-condensed table-hover\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>Day | Hours</th>\r\n");

            
            #line 42 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0;hours<24;hours++) {

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Report\calender.cshtml"
                             Write(hours);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 44 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(">Count</th>\r\n        <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(">Amount</th>\r\n    </tr>\r\n    </thead>\r\n");

            
            #line 49 "..\..\Views\Report\calender.cshtml"
    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Report\calender.cshtml"
     for (int day = 1; day <= DateTime.DaysInMonth(year, ViewBag.month); day++)
    {
        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Report\calender.cshtml"
           DateTime dayDT = new DateTime(year, ViewBag.month, day); string sDay = dayDT.DayOfWeek.ToString();  
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Report\calender.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n");

            
            #line 53 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Report\calender.cshtml"
             if (dayDT.DayOfWeek == DayOfWeek.Saturday || dayDT.DayOfWeek == DayOfWeek.Sunday)
            {
                colourRow = true;

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 56 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 56 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 57 "..\..\Views\Report\calender.cshtml"
            } else
            {
                colourRow = false;

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 60 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 60 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>            \r\n");

            
            #line 61 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("           ");

            
            #line 62 "..\..\Views\Report\calender.cshtml"
            for (int hour = 0; hour < 24; hour++)
           {
               List<ViewHeaderBatch> batches = new List<ViewHeaderBatch>();
               int latestBatchNo = 0;
               name = string.Empty;
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour))
               {
                   var data = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour);
                   foreach (var batch in data)
                   {
                       if (batch.Need != 0)
                       {
                           amnt = batch.Need / 1000;
                           amntTotal += amnt;
                       }
                       if (batch.BatchNo != latestBatchNo && (batch.RecordType != Operations.RecipeEnd))
                       {

                           batches.Add(new ViewHeaderBatch() { Name = batch.Destination, BatchNo = batch.BatchNo, AmntTotal = amnt, RecipeNo = batch.Variant1});
                           count++;
                       }
                       latestBatchNo = batch.BatchNo;
                   }
               }
               if (colourRow == true)
               {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgoldenrodyellow\"");

WriteLiteral(">\r\n");

            
            #line 89 "..\..\Views\Report\calender.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Report\calender.cshtml"
                     foreach (var batch in batches)
                    {
                        if (Model.Data.Exists(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd))
                        {
                            EndType = Model.Data.Single(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd).Variant2; // takes endType
                        }
                        batch.Status = Convert.ToBoolean(EndType);
                        if (batch.Status != false)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 3853), Tuple.Create("\"", 3889)
, Tuple.Create(Tuple.Create("", 3860), Tuple.Create("/Report/Detail/", 3860), true)
            
            #line 98 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 3875), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 3875), false)
);

WriteLiteral(" style=\"color: darkgreen;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3916), Tuple.Create("\"", 4005)
, Tuple.Create(Tuple.Create("", 3924), Tuple.Create("Batch:", 3924), true)
            
            #line 98 "..\..\Views\Report\calender.cshtml"
                              , Tuple.Create(Tuple.Create(" ", 3930), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 3931), false)
, Tuple.Create(Tuple.Create("  ", 3945), Tuple.Create("Recipe:", 3947), true)
            
            #line 98 "..\..\Views\Report\calender.cshtml"
                                                      , Tuple.Create(Tuple.Create(" ", 3954), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 3955), false)
, Tuple.Create(Tuple.Create(" ", 3970), Tuple.Create("Filled", 3971), true)
, Tuple.Create(Tuple.Create(" ", 3977), Tuple.Create("amount:", 3978), true)
            
            #line 98 "..\..\Views\Report\calender.cshtml"
                                                                                     , Tuple.Create(Tuple.Create(" ", 3985), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 3986), false)
, Tuple.Create(Tuple.Create(" ", 4002), Tuple.Create("kg", 4003), true)
);

WriteLiteral(">");

            
            #line 98 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                      Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 99 "..\..\Views\Report\calender.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 4145), Tuple.Create("\"", 4181)
, Tuple.Create(Tuple.Create("", 4152), Tuple.Create("/Report/Detail/", 4152), true)
            
            #line 102 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 4167), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 4167), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 4182), Tuple.Create("\"", 4271)
, Tuple.Create(Tuple.Create("", 4190), Tuple.Create("Batch:", 4190), true)
            
            #line 102 "..\..\Views\Report\calender.cshtml"
    , Tuple.Create(Tuple.Create(" ", 4196), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 4197), false)
, Tuple.Create(Tuple.Create("  ", 4211), Tuple.Create("Recipe:", 4213), true)
            
            #line 102 "..\..\Views\Report\calender.cshtml"
                            , Tuple.Create(Tuple.Create(" ", 4220), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 4221), false)
, Tuple.Create(Tuple.Create(" ", 4236), Tuple.Create("Filled", 4237), true)
, Tuple.Create(Tuple.Create(" ", 4243), Tuple.Create("amount:", 4244), true)
            
            #line 102 "..\..\Views\Report\calender.cshtml"
                                                           , Tuple.Create(Tuple.Create(" ", 4251), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 4252), false)
, Tuple.Create(Tuple.Create(" ", 4268), Tuple.Create("kg", 4269), true)
);

WriteLiteral(">");

            
            #line 102 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                            Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 103 "..\..\Views\Report\calender.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 106 "..\..\Views\Report\calender.cshtml"
               }
               else
               {

            
            #line default
            #line hidden
WriteLiteral("                <td>\r\n");

            
            #line 110 "..\..\Views\Report\calender.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 110 "..\..\Views\Report\calender.cshtml"
                     foreach (var batch in batches)
                    {
                        if (Model.Data.Exists(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd))
                        {
                            EndType = Model.Data.Single(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd).Variant2; // takes endType
                        }
                        batch.Status = Convert.ToBoolean(EndType);
                        if (batch.Status != false)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5034), Tuple.Create("\"", 5070)
, Tuple.Create(Tuple.Create("", 5041), Tuple.Create("/Report/Detail/", 5041), true)
            
            #line 119 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 5056), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 5056), false)
);

WriteLiteral(" style=\"color: darkgreen;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 5097), Tuple.Create("\"", 5186)
, Tuple.Create(Tuple.Create("", 5105), Tuple.Create("Batch:", 5105), true)
            
            #line 119 "..\..\Views\Report\calender.cshtml"
                              , Tuple.Create(Tuple.Create(" ", 5111), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 5112), false)
, Tuple.Create(Tuple.Create("  ", 5126), Tuple.Create("Recipe:", 5128), true)
            
            #line 119 "..\..\Views\Report\calender.cshtml"
                                                      , Tuple.Create(Tuple.Create(" ", 5135), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 5136), false)
, Tuple.Create(Tuple.Create(" ", 5151), Tuple.Create("Filled", 5152), true)
, Tuple.Create(Tuple.Create(" ", 5158), Tuple.Create("amount:", 5159), true)
            
            #line 119 "..\..\Views\Report\calender.cshtml"
                                                                                     , Tuple.Create(Tuple.Create(" ", 5166), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 5167), false)
, Tuple.Create(Tuple.Create(" ", 5183), Tuple.Create("kg", 5184), true)
);

WriteLiteral(">");

            
            #line 119 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                      Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 120 "..\..\Views\Report\calender.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5326), Tuple.Create("\"", 5362)
, Tuple.Create(Tuple.Create("", 5333), Tuple.Create("/Report/Detail/", 5333), true)
            
            #line 123 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 5348), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 5348), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 5363), Tuple.Create("\"", 5452)
, Tuple.Create(Tuple.Create("", 5371), Tuple.Create("Batch:", 5371), true)
            
            #line 123 "..\..\Views\Report\calender.cshtml"
    , Tuple.Create(Tuple.Create(" ", 5377), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 5378), false)
, Tuple.Create(Tuple.Create("  ", 5392), Tuple.Create("Recipe:", 5394), true)
            
            #line 123 "..\..\Views\Report\calender.cshtml"
                            , Tuple.Create(Tuple.Create(" ", 5401), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 5402), false)
, Tuple.Create(Tuple.Create(" ", 5417), Tuple.Create("Filled", 5418), true)
, Tuple.Create(Tuple.Create(" ", 5424), Tuple.Create("amount:", 5425), true)
            
            #line 123 "..\..\Views\Report\calender.cshtml"
                                                           , Tuple.Create(Tuple.Create(" ", 5432), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 5433), false)
, Tuple.Create(Tuple.Create(" ", 5449), Tuple.Create("kg", 5450), true)
);

WriteLiteral(">");

            
            #line 123 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                            Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 124 "..\..\Views\Report\calender.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 127 "..\..\Views\Report\calender.cshtml"
               }
           }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 129 "..\..\Views\Report\calender.cshtml"
             if (count != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral("  style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral(">");

            
            #line 131 "..\..\Views\Report\calender.cshtml"
                                                                         Write(count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 132 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 134 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 135 "..\..\Views\Report\calender.cshtml"
              countOverall += count; count = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 136 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 136 "..\..\Views\Report\calender.cshtml"
             if (amntTotal != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 138 "..\..\Views\Report\calender.cshtml"
                                                                         Write(amntTotal);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 139 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 141 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 142 "..\..\Views\Report\calender.cshtml"
              amntOverall += amntTotal; amntTotal = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </tr>\r\n");

            
            #line 144 "..\..\Views\Report\calender.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><b>Total</b></td>\r\n");

            
            #line 147 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 147 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0; hours < 24; hours++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 150 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <td><b>");

            
            #line 151 "..\..\Views\Report\calender.cshtml"
          Write(countOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td><b>");

            
            #line 152 "..\..\Views\Report\calender.cshtml"
          Write(amntOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n    </tr>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
