#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\Report\calender.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\Report\calender.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    #line 3 "..\..\Views\Report\calender.cshtml"
    using UsersDiosna.Report.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Report/calender.cshtml")]
    public partial class _Views_Report_calender_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Report.Models.DataReportModel>
    {
        public _Views_Report_calender_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Report\calender.cshtml"
  
    ViewBag.Title = "calender";
    string name = string.Empty;
    int EndType = 0;
    int amntTotal = 0;
    int amntOverall= 0;
    int amnt = 0;
    string colourRow = "white";
    int count = 0;
    int countOverall = 0;
    int dosingOutCount = 0;
    int dosingOutAmountSum = 0;
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    int cleaningCount = 0;
    /*
    int rowDOcount = 0;
    int rowDOamount = 0;
    int rowDOcountOverall = 0;
    int rowDOamountOverall = 0;
    */
    int year = ViewBag.year;
    int yearOnButtonLeft = year;
    int yearOnButtonRight = year;
    int monthLess = ViewBag.Month - 1;
    int monthMore = ViewBag.Month + 1;
    if (monthLess < 1) {
        yearOnButtonLeft--;
        monthLess = 12;
    }
    if (monthMore > 12) {
        yearOnButtonRight++;
        monthMore = 1;
    }
    ViewHeaderDosingOut dosingOut = null;
    ViewHeaderCleaning cleaning = null;
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    DateTime monthDT = new DateTime(year, ViewBag.month, 1);
    string monthName = monthDT.ToString("MMMM");


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Calender</h4>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1424), Tuple.Create("\"", 1473)
, Tuple.Create(Tuple.Create("", 1431), Tuple.Create("/Report/Month/", 1431), true)
            
            #line 52 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1445), Tuple.Create<System.Object, System.Int32>(monthLess
            
            #line default
            #line hidden
, 1445), false)
, Tuple.Create(Tuple.Create("", 1455), Tuple.Create("/", 1455), true)
            
            #line 52 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 1456), Tuple.Create<System.Object, System.Int32>(yearOnButtonLeft
            
            #line default
            #line hidden
, 1456), false)
);

WriteLiteral(">-1 month</a> Month: ");

            
            #line 52 "..\..\Views\Report\calender.cshtml"
                                                                                                   Write(monthName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 52 "..\..\Views\Report\calender.cshtml"
                                                                                                              Write(year);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1541), Tuple.Create("\"", 1591)
, Tuple.Create(Tuple.Create("", 1548), Tuple.Create("/Report/Month/", 1548), true)
            
            #line 52 "..\..\Views\Report\calender.cshtml"
                                                                                           , Tuple.Create(Tuple.Create("", 1562), Tuple.Create<System.Object, System.Int32>(monthMore
            
            #line default
            #line hidden
, 1562), false)
, Tuple.Create(Tuple.Create("", 1572), Tuple.Create("/", 1572), true)
            
            #line 52 "..\..\Views\Report\calender.cshtml"
                                                                                                      , Tuple.Create(Tuple.Create("", 1573), Tuple.Create<System.Object, System.Int32>(yearOnButtonRight
            
            #line default
            #line hidden
, 1573), false)
);

WriteLiteral(">+1 month</a>\r\n    <p></p>\r\n</div>\r\n<div");

WriteLiteral(" class=\" col-md-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowBatches()\"");

WriteLiteral(" checked />Show Batches\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowDosing()\"");

WriteLiteral(" />Show Dosing\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"checkbox-inline big-checkbox\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" onclick=\"hideShowCleaning()\"");

WriteLiteral(" />Show Cleaning\r\n    </div>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table-bordered table-condensed\"");

WriteLiteral(">\r\n    <thead>\r\n    <tr>\r\n        <th>Day | Hours</th>\r\n");

            
            #line 70 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 70 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0;hours<24;hours++) {

            
            #line default
            #line hidden
WriteLiteral("            <th");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral(">");

            
            #line 71 "..\..\Views\Report\calender.cshtml"
                             Write(hours);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 72 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Batches Count\"");

WriteLiteral(">B. cnt.</th>\r\n        <th");

WriteLiteral(" style=\"background-color: lightcyan;\"");

WriteLiteral(" title=\"Dosing Count\"");

WriteLiteral(">DO. cnt.</th>\r\n        <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Batches amount\"");

WriteLiteral(">B. amt.</th>       \r\n        <th");

WriteLiteral(" style=\"background-color: lightgray;\"");

WriteLiteral(" title=\"Dosing amount\"");

WriteLiteral(">DO. amt.</th>\r\n    </tr>\r\n    </thead>\r\n");

            
            #line 79 "..\..\Views\Report\calender.cshtml"
    
            
            #line default
            #line hidden
            
            #line 79 "..\..\Views\Report\calender.cshtml"
     for (int day = 1; day <= DateTime.DaysInMonth(year, ViewBag.month); day++)
    {
        
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Report\calender.cshtml"
           DateTime dayDT = new DateTime(year, ViewBag.month, day); string sDay = dayDT.DayOfWeek.ToString();  
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\Report\calender.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n");

            
            #line 83 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Report\calender.cshtml"
             if (dayDT.DayOfWeek == DayOfWeek.Saturday || dayDT.DayOfWeek == DayOfWeek.Sunday)
            {
                colourRow = "lightgoldenrodyellow";

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 86 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 86 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 87 "..\..\Views\Report\calender.cshtml"
            }
            else
            {
                colourRow = "white";

            
            #line default
            #line hidden
WriteLiteral("                <td>");

            
            #line 91 "..\..\Views\Report\calender.cshtml"
               Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 91 "..\..\Views\Report\calender.cshtml"
                     Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>            \r\n");

            
            #line 92 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("           ");

            
            #line 93 "..\..\Views\Report\calender.cshtml"
            for (int hour = 0; hour < 24; hour++)
           {
               List<ViewHeaderBatch> batches = new List<ViewHeaderBatch>();
               int latestBatchNo = 0;
               name = string.Empty;
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour))
               {
                   var data = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType != Operations.DosingOut);
                   foreach (var batch in data)
                   {
                       if (batch.Need != 0)
                       {
                           amnt = batch.Need / 1000;
                           amntTotal += amnt;
                       }
                       if (batch.BatchNo != latestBatchNo && (batch.RecordType == Operations.RecipeStart))
                       {

                           batches.Add(new ViewHeaderBatch() { Name = batch.Destination, BatchNo = batch.BatchNo, AmntTotal = amnt, RecipeNo = batch.Variant1});
                           count++;
                       }
                       latestBatchNo = batch.BatchNo;
                   }
               }
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut))
               {
                   dosingOutCount = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Count();
                   dosingOutAmountSum = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && p.RecordType == Operations.DosingOut).Sum(p => p.Actual);
                   dosingOut = new ViewHeaderDosingOut { hour = hour, count = dosingOutCount, amountSum = dosingOutAmountSum};
               }
               if (Model.Data.Exists(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.Cleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning)))
               {
                   var cleanings = Model.Data.Where(p => p.TimeStart.Day == day && p.TimeStart.Hour == hour && (p.RecordType == Operations.Cleaning || p.RecordType == Operations.PipWorkCleaning || p.RecordType == Operations.YeastCleaning));
                   foreach (var cleanOp in cleanings) {
                       if (cleanOp.RecordType == Operations.Pigging) {
                           cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = ClnType.none, StartedBy = (StartedBy)cleanOp.Variant2 };
                       }
                       else {
                           cleaning = new ViewHeaderCleaning { cleaning = cleanOp.RecordType.ToString(), destination = cleanOp.Destination, BatchNo = cleanOp.BatchNo, ClnType = (ClnType)cleanOp.Variant1, StartedBy = (StartedBy)cleanOp.Variant2 };
                       }
                   }
               }

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteAttribute("style", Tuple.Create(" style=\"", 6312), Tuple.Create("\"", 6348)
, Tuple.Create(Tuple.Create("", 6320), Tuple.Create("background-color:", 6320), true)
            
            #line 135 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create(" ", 6337), Tuple.Create<System.Object, System.Int32>(colourRow
            
            #line default
            #line hidden
, 6338), false)
);

WriteLiteral(">\r\n");

            
            #line 136 "..\..\Views\Report\calender.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 136 "..\..\Views\Report\calender.cshtml"
                     foreach (var batch in batches)
                    {
                        if (Model.Data.Exists(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd))
                        {
                            EndType = Model.Data.First(p => p.BatchNo == batch.BatchNo && p.RecordType == Operations.RecipeEnd).Variant2; // takes endType
                        }
                        batch.Status = Convert.ToBoolean(EndType);
                        if (batch.Status != false)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6939), Tuple.Create("\"", 6975)
, Tuple.Create(Tuple.Create("", 6946), Tuple.Create("/Report/Detail/", 6946), true)
            
            #line 145 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 6961), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 6961), false)
);

WriteLiteral(" class=\"batch\"");

WriteLiteral(" style=\"color: darkgreen;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7016), Tuple.Create("\"", 7105)
, Tuple.Create(Tuple.Create("", 7024), Tuple.Create("Batch:", 7024), true)
            
            #line 145 "..\..\Views\Report\calender.cshtml"
                                            , Tuple.Create(Tuple.Create(" ", 7030), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7031), false)
, Tuple.Create(Tuple.Create("  ", 7045), Tuple.Create("Recipe:", 7047), true)
            
            #line 145 "..\..\Views\Report\calender.cshtml"
                                                                    , Tuple.Create(Tuple.Create(" ", 7054), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 7055), false)
, Tuple.Create(Tuple.Create(" ", 7070), Tuple.Create("Filled", 7071), true)
, Tuple.Create(Tuple.Create(" ", 7077), Tuple.Create("amount:", 7078), true)
            
            #line 145 "..\..\Views\Report\calender.cshtml"
                                                                                                   , Tuple.Create(Tuple.Create(" ", 7085), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7086), false)
, Tuple.Create(Tuple.Create(" ", 7102), Tuple.Create("kg", 7103), true)
);

WriteLiteral(">");

            
            #line 145 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                    Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 146 "..\..\Views\Report\calender.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <b><a");

WriteAttribute("href", Tuple.Create(" href=\"", 7245), Tuple.Create("\"", 7281)
, Tuple.Create(Tuple.Create("", 7252), Tuple.Create("/Report/Detail/", 7252), true)
            
            #line 149 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7267), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7267), false)
);

WriteLiteral(" class=\"batch\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7296), Tuple.Create("\"", 7385)
, Tuple.Create(Tuple.Create("", 7304), Tuple.Create("Batch:", 7304), true)
            
            #line 149 "..\..\Views\Report\calender.cshtml"
                  , Tuple.Create(Tuple.Create(" ", 7310), Tuple.Create<System.Object, System.Int32>(batch.BatchNo
            
            #line default
            #line hidden
, 7311), false)
, Tuple.Create(Tuple.Create("  ", 7325), Tuple.Create("Recipe:", 7327), true)
            
            #line 149 "..\..\Views\Report\calender.cshtml"
                                          , Tuple.Create(Tuple.Create(" ", 7334), Tuple.Create<System.Object, System.Int32>(batch.RecipeNo
            
            #line default
            #line hidden
, 7335), false)
, Tuple.Create(Tuple.Create(" ", 7350), Tuple.Create("Filled", 7351), true)
, Tuple.Create(Tuple.Create(" ", 7357), Tuple.Create("amount:", 7358), true)
            
            #line 149 "..\..\Views\Report\calender.cshtml"
                                                                         , Tuple.Create(Tuple.Create(" ", 7365), Tuple.Create<System.Object, System.Int32>(batch.AmntTotal
            
            #line default
            #line hidden
, 7366), false)
, Tuple.Create(Tuple.Create(" ", 7382), Tuple.Create("kg", 7383), true)
);

WriteLiteral(">");

            
            #line 149 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                          Write(batch.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 150 "..\..\Views\Report\calender.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 152 "..\..\Views\Report\calender.cshtml"
                     if (dosingOut != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7552), Tuple.Create("\"", 7602)
, Tuple.Create(Tuple.Create("", 7559), Tuple.Create("/ReportDosing/Day/", 7559), true)
            
            #line 154 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7577), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 7577), false)
, Tuple.Create(Tuple.Create("", 7581), Tuple.Create("/", 7581), true)
            
            #line 154 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7582), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 7582), false)
, Tuple.Create(Tuple.Create("", 7596), Tuple.Create("/", 7596), true)
            
            #line 154 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 7597), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 7597), false)
);

WriteLiteral(" class=\"dosing\"");

WriteAttribute("title", Tuple.Create(" title=\"", 7618), Tuple.Create("\"", 7670)
, Tuple.Create(Tuple.Create("", 7626), Tuple.Create("Total", 7626), true)
, Tuple.Create(Tuple.Create(" ", 7631), Tuple.Create("Amount:", 7632), true)
            
            #line 154 "..\..\Views\Report\calender.cshtml"
                                  , Tuple.Create(Tuple.Create(" ", 7639), Tuple.Create<System.Object, System.Int32>(dosingOut.amountSum/1000
            
            #line default
            #line hidden
, 7640), false)
, Tuple.Create(Tuple.Create(" ", 7667), Tuple.Create("kg", 7668), true)
);

WriteLiteral(">(<b>");

            
            #line 154 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                 Write(dosingOut.count);

            
            #line default
            #line hidden
WriteLiteral("</b>)</a>\r\n");

            
            #line 155 "..\..\Views\Report\calender.cshtml"
                        rowDOcount += dosingOut.count;
                        rowDOamount += (dosingOut.amountSum/1000);
                        dosingOut = null;
                    }

            
            #line default
            #line hidden
WriteLiteral("                    ");

            
            #line 159 "..\..\Views\Report\calender.cshtml"
                     if (cleaning != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7986), Tuple.Create("\"", 8038)
, Tuple.Create(Tuple.Create("", 7993), Tuple.Create("/ReportCleaning/Day/", 7993), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8013), Tuple.Create<System.Object, System.Int32>(day
            
            #line default
            #line hidden
, 8013), false)
, Tuple.Create(Tuple.Create("", 8017), Tuple.Create("/", 8017), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8018), Tuple.Create<System.Object, System.Int32>(ViewBag.Month
            
            #line default
            #line hidden
, 8018), false)
, Tuple.Create(Tuple.Create("", 8032), Tuple.Create("/", 8032), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
, Tuple.Create(Tuple.Create("", 8033), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 8033), false)
);

WriteLiteral(" class=\"cleaning\"");

WriteAttribute("title", Tuple.Create(" title=\"", 8056), Tuple.Create("\"", 8176)
, Tuple.Create(Tuple.Create("", 8064), Tuple.Create("Cleaning:", 8064), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
                                 , Tuple.Create(Tuple.Create(" ", 8073), Tuple.Create<System.Object, System.Int32>(cleaning.cleaning
            
            #line default
            #line hidden
, 8074), false)
, Tuple.Create(Tuple.Create(" ", 8092), Tuple.Create("Clean", 8093), true)
, Tuple.Create(Tuple.Create(" ", 8098), Tuple.Create("Type:", 8099), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
                                                                , Tuple.Create(Tuple.Create(" ", 8104), Tuple.Create<System.Object, System.Int32>(cleaning.ClnType.ToString()
            
            #line default
            #line hidden
, 8105), false)
, Tuple.Create(Tuple.Create(" ", 8133), Tuple.Create("Started", 8134), true)
, Tuple.Create(Tuple.Create(" ", 8141), Tuple.Create("By:", 8142), true)
            
            #line 161 "..\..\Views\Report\calender.cshtml"
                                                                                                         , Tuple.Create(Tuple.Create(" ", 8145), Tuple.Create<System.Object, System.Int32>(cleaning.StartedBy.ToString()
            
            #line default
            #line hidden
, 8146), false)
);

WriteLiteral(">[<b>");

            
            #line 161 "..\..\Views\Report\calender.cshtml"
                                                                                                                                                                                                                         Write(cleaning.destination);

            
            #line default
            #line hidden
WriteLiteral("</b>]</a>\r\n");

            
            #line 162 "..\..\Views\Report\calender.cshtml"
                        cleaning = null;
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n");

            
            #line 165 "..\..\Views\Report\calender.cshtml"
           }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 166 "..\..\Views\Report\calender.cshtml"
             if (count != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral("  style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral(">");

            
            #line 168 "..\..\Views\Report\calender.cshtml"
                                                                         Write(count);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 169 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 171 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 172 "..\..\Views\Report\calender.cshtml"
              countOverall += count; count = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 173 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 173 "..\..\Views\Report\calender.cshtml"
             if (rowDOcount != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center; \"");

WriteLiteral(">");

            
            #line 175 "..\..\Views\Report\calender.cshtml"
                                                                         Write(rowDOcount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 176 "..\..\Views\Report\calender.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightcyan; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 180 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 181 "..\..\Views\Report\calender.cshtml"
               rowDOcountOverall += rowDOcount; rowDOcount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 182 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 182 "..\..\Views\Report\calender.cshtml"
             if (amntTotal != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 184 "..\..\Views\Report\calender.cshtml"
                                                                         Write(amntTotal);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 185 "..\..\Views\Report\calender.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 187 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 188 "..\..\Views\Report\calender.cshtml"
              amntOverall += amntTotal; amntTotal = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 189 "..\..\Views\Report\calender.cshtml"
            
            
            #line default
            #line hidden
            
            #line 189 "..\..\Views\Report\calender.cshtml"
             if (rowDOamount != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center; \"");

WriteLiteral(">");

            
            #line 191 "..\..\Views\Report\calender.cshtml"
                                                                         Write(rowDOamount);

            
            #line default
            #line hidden
WriteLiteral(" kg</td>\r\n");

            
            #line 192 "..\..\Views\Report\calender.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <td");

WriteLiteral(" style=\"background-color: lightgray; text-align: center;\"");

WriteLiteral("></td>\r\n");

            
            #line 196 "..\..\Views\Report\calender.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 197 "..\..\Views\Report\calender.cshtml"
               rowDOamountOverall += rowDOamount; rowDOamount = 0; 
            
            #line default
            #line hidden
WriteLiteral("\r\n        </tr>\r\n");

            
            #line 199 "..\..\Views\Report\calender.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><b>Total</b></td>\r\n");

            
            #line 202 "..\..\Views\Report\calender.cshtml"
        
            
            #line default
            #line hidden
            
            #line 202 "..\..\Views\Report\calender.cshtml"
         for (int hours = 0; hours < 24; hours++)
        {

            
            #line default
            #line hidden
WriteLiteral("            <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 205 "..\..\Views\Report\calender.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 206 "..\..\Views\Report\calender.cshtml"
                                      Write(countOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 207 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOcountOverall);

            
            #line default
            #line hidden
WriteLiteral("</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 208 "..\..\Views\Report\calender.cshtml"
                                      Write(amntOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n        <td");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral("><b>");

            
            #line 209 "..\..\Views\Report\calender.cshtml"
                                      Write(rowDOamountOverall);

            
            #line default
            #line hidden
WriteLiteral(" kg</b></td>\r\n    </tr>\r\n</table>");

        }
    }
}
#pragma warning restore 1591
