#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/GuestZone.cshtml")]
    public partial class _Views_Home_GuestZone_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_GuestZone_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\GuestZone.cshtml"
  
    ViewBag.Title = "Guest Zone";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Guest Zone</h2>\r\n<h6>Read general articles in our knowledge base: </h6>\r\n<d" +
"iv");

WriteLiteral(" class=\"well\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"btn-group btn-group-justified\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"/Home/\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Free documnets and info&rAarr;</a>\r\n    </div>\r\n</div>\r\n<h6>About us and our par" +
"tners</h6>\r\n<div");

WriteLiteral(" class=\"well\"");

WriteLiteral(" style=\"background-color: white;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"http://www.diosna.com/\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" src=\"../img/diosna.jpg\"");

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"Diosna\"");

WriteLiteral(" />\r\n    </a>\r\n    <a");

WriteLiteral(" href=\"http://www.isernhaeger.de/\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" src=\"../img/isernhager.png\"");

WriteLiteral(" class=\"img-rounded\"");

WriteLiteral(" alt=\"Iserngaer\"");

WriteLiteral(" />\r\n    </a>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
