#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Homepage";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Homepage</h2>\r\n<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    ");

WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Home\Index.cshtml"
     if (!(Request.IsAuthenticated))
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">This is welcome screen please ");

            
            #line 11 "..\..\Views\Home\Index.cshtml"
                                                 Write(Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" }));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 12 "..\..\Views\Home\Index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">If you want to continue into your bakery please ");

            
            #line 15 "..\..\Views\Home\Index.cshtml"
                                                                   Write(Html.ActionLink("click here", "Homepage", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 16 "..\..\Views\Home\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Errors</h2>\r\n        <p>\r\n            Have you find a bug in this " +
"system?<br>\r\n            Pleease write this bug as issue into our issue system\r\n" +
"        </p>\r\n        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"https://github.com/Sidmarek/MVCTutorial/issues\"");

WriteLiteral(">Add Issue &raquo;</a></p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(@">
        <h2>News</h2>
        <p>
            In latest update have been add following features:<br>
            Changes commit:  …<br>
            graph getData finished<br>
            graph getData async done<br>
            graph client signals drawed<br>
            menu small style changes<br>
        </p>
        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://192.168.2.13/Home/News\"");

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Link to old users.nordit.cz</h2>\r\n        <p>If you need old users" +
" click below</p>\r\n        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://users.nordit.cz/\"");

WriteLiteral(">Bye &raquo;</a></p>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
