#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    
    #line 1 "..\..\Views\Alarm_Old\Index.cshtml"
    using UsersDiosna.Alarms.Models;
    
    #line default
    #line hidden
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Alarm_Old/Index.cshtml")]
    public partial class _Views_Alarm_Old_Index_cshtml : System.Web.Mvc.WebViewPage<AlarmFormModel>
    {
        public _Views_Alarm_Old_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Alarm_Old\Index.cshtml"
  
    ViewBag.Title = "Alarms";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2");

WriteLiteral(" class=\"header\"");

WriteLiteral(">Alarms</h2>\r\n\r\n");

            
            #line 10 "..\..\Views\Alarm_Old\Index.cshtml"
Write(Html.Partial("~/Views/Alarm/_Form.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Alarm_Old\Index.cshtml"
Write(Html.Partial("~/Views/Alarm/_Content.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<p");

WriteLiteral(" class=\"left\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("href", Tuple.Create(" href=\"", 274), Tuple.Create("\"", 369)
, Tuple.Create(Tuple.Create("", 281), Tuple.Create("/AlarmNotification/All?name=", 281), true)
            
            #line 13 "..\..\Views\Alarm_Old\Index.cshtml"
, Tuple.Create(Tuple.Create("", 309), Tuple.Create<System.Object, System.Int32>(Request.QueryString["name"]
            
            #line default
            #line hidden
, 309), false)
, Tuple.Create(Tuple.Create("", 337), Tuple.Create("&plc=", 337), true)
            
            #line 13 "..\..\Views\Alarm_Old\Index.cshtml"
                   , Tuple.Create(Tuple.Create("", 342), Tuple.Create<System.Object, System.Int32>(Request.QueryString["plc"]
            
            #line default
            #line hidden
, 342), false)
);

WriteLiteral(">Notification from all alarms</a>\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
