#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Menu/_Menu.cshtml")]
    public partial class _Views_Menu__Menu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Menu__Menu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"sidenav a\"");

WriteLiteral(">\r\n");

            
            #line 2 "..\..\Views\Menu\_Menu.cshtml"
  
    ViewBag.Names = Session["names"];
    ViewBag.plc = Session["plc"];
    ViewBag.id = Session["id"];
    ViewBag.types = Session["types"];
    ViewBag.ProjectName = Session["ProjectName"];
    int i = 0;
    int j = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<a");

WriteAttribute("href", Tuple.Create(" href=\"", 263), Tuple.Create("\"", 293)
, Tuple.Create(Tuple.Create("", 270), Tuple.Create("/Menu/Index/", 270), true)
            
            #line 11 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 282), Tuple.Create<System.Object, System.Int32>(ViewBag.id
            
            #line default
            #line hidden
, 282), false)
);

WriteLiteral(" class=\"projectName\"");

WriteLiteral(" style=\"color:white;\"");

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Menu\_Menu.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Menu\_Menu.cshtml"
     if (ViewBag.ProjectName != null) {
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Menu\_Menu.cshtml"
   Write(ViewBag.ProjectName.ToString());

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Menu\_Menu.cshtml"
                                       
    }
            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 15 "..\..\Views\Menu\_Menu.cshtml"
 foreach (String type in ViewBag.types)
{
    if (type.Contains("plc"))    {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"plc\"");

WriteLiteral(">");

            
            #line 18 "..\..\Views\Menu\_Menu.cshtml"
                     Write(ViewBag.plc[i]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 19 "..\..\Views\Menu\_Menu.cshtml"
        i++;
    } else {
        if (i == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 635), Tuple.Create("\"", 692)
, Tuple.Create(Tuple.Create("", 642), Tuple.Create("/", 642), true)
            
            #line 23 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 643), Tuple.Create<System.Object, System.Int32>(type
            
            #line default
            #line hidden
, 643), false)
, Tuple.Create(Tuple.Create("", 648), Tuple.Create("?&name=", 648), true)
            
            #line 23 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 655), Tuple.Create<System.Object, System.Int32>(ViewBag.names[j]
            
            #line default
            #line hidden
, 655), false)
, Tuple.Create(Tuple.Create("", 672), Tuple.Create("&plc=", 672), true)
            
            #line 23 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 677), Tuple.Create<System.Object, System.Int32>(ViewBag.plc[i]
            
            #line default
            #line hidden
, 677), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\Menu\_Menu.cshtml"
                                                                    Write(ViewBag.names[j]);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 24 "..\..\Views\Menu\_Menu.cshtml"
        }
        else
        {
            i--;

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 785), Tuple.Create("\"", 841)
, Tuple.Create(Tuple.Create("", 792), Tuple.Create("/", 792), true)
            
            #line 28 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 793), Tuple.Create<System.Object, System.Int32>(type
            
            #line default
            #line hidden
, 793), false)
, Tuple.Create(Tuple.Create("", 798), Tuple.Create("?name=", 798), true)
            
            #line 28 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 804), Tuple.Create<System.Object, System.Int32>(ViewBag.names[j]
            
            #line default
            #line hidden
, 804), false)
, Tuple.Create(Tuple.Create("", 821), Tuple.Create("&plc=", 821), true)
            
            #line 28 "..\..\Views\Menu\_Menu.cshtml"
, Tuple.Create(Tuple.Create("", 826), Tuple.Create<System.Object, System.Int32>(ViewBag.plc[i]
            
            #line default
            #line hidden
, 826), false)
);

WriteLiteral(">");

            
            #line 28 "..\..\Views\Menu\_Menu.cshtml"
                                                                   Write(ViewBag.names[j]);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 29 "..\..\Views\Menu\_Menu.cshtml"
            i++;
        }
        j++;
    }
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
