#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Download/Index.cshtml")]
    public partial class _Views_Download_Index_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.File.Models.FileFormModel>
    {
        public _Views_Download_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Download\Index.cshtml"
   
    ViewBag.Title = "Downloads";
    string fileName;
    int iHelper;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 7 "..\..\Views\Download\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 8 "..\..\Views\Download\Index.cshtml"
 if(ViewBag.files !=null) { 
    foreach (string file in ViewBag.files)
    {
        if (file.Contains(@"\"))
        {
            iHelper = file.LastIndexOf(@"\");
            fileName = file.Substring(iHelper + 1);
            ViewBag.fileName = fileName;

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"list-group-item-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Download\Index.cshtml"
           Write(ViewBag.fileName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 522), Tuple.Create("\"", 566)
, Tuple.Create(Tuple.Create("", 529), Tuple.Create("/Download/downloadFile?nameFile=", 529), true)
            
            #line 18 "..\..\Views\Download\Index.cshtml"
, Tuple.Create(Tuple.Create("", 561), Tuple.Create<System.Object, System.Int32>(file
            
            #line default
            #line hidden
, 561), false)
);

WriteLiteral(">Download</a>\r\n");

            
            #line 19 "..\..\Views\Download\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Download\Index.cshtml"
                 if (file.Contains(".pdf") || file.Contains(".txt"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 693), Tuple.Create("\"", 744)
, Tuple.Create(Tuple.Create("", 700), Tuple.Create("/Download/downloadFile?nameFile=", 700), true)
            
            #line 21 "..\..\Views\Download\Index.cshtml"
, Tuple.Create(Tuple.Create("", 732), Tuple.Create<System.Object, System.Int32>(file
            
            #line default
            #line hidden
, 732), false)
, Tuple.Create(Tuple.Create("", 737), Tuple.Create("&View=1", 737), true)
);

WriteLiteral(">View</a>");

WriteLiteral("<br>\r\n");

            
            #line 22 "..\..\Views\Download\Index.cshtml"
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <br>\r\n");

            
            #line 26 "..\..\Views\Download\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");

            
            #line 28 "..\..\Views\Download\Index.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"list-group-item-heading\"");

WriteLiteral("><b>");

            
            #line 31 "..\..\Views\Download\Index.cshtml"
                                           Write(file);

            
            #line default
            #line hidden
WriteLiteral("</b><br></div>\r\n");

            
            #line 32 "..\..\Views\Download\Index.cshtml"
        }
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">No files has been found</div>\r\n");

            
            #line 38 "..\..\Views\Download\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 42 "..\..\Views\Download\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
