#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Download/Index.cshtml")]
    public partial class _Views_Download_Index_cshtml : System.Web.Mvc.WebViewPage<List<UsersDiosna.Download.Models.FileForDownload>>
    {
        public _Views_Download_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Download\Index.cshtml"
   
    ViewBag.Title = "Downloads";
    string fileName;
    int iHelper;
    int i = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 8 "..\..\Views\Download\Index.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 9 "..\..\Views\Download\Index.cshtml"
 if (Model != null)
{
    foreach (UsersDiosna.Download.Models.FileForDownload filesForMask in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"list-group-item-heading\"");

WriteLiteral("><b>");

            
            #line 13 "..\..\Views\Download\Index.cshtml"
                                           Write(filesForMask.maskName);

            
            #line default
            #line hidden
WriteLiteral("</b><br></div>\r\n");

            
            #line 14 "..\..\Views\Download\Index.cshtml"
        foreach (string file in filesForMask.files)
        {
            iHelper = file.LastIndexOf(@"\");
            fileName = file.Substring(iHelper + 1);

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"list-group-item-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Download\Index.cshtml"
           Write(fileName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 636), Tuple.Create("\"", 698)
, Tuple.Create(Tuple.Create("", 643), Tuple.Create("/Download/downloadFile?nameFile=", 643), true)
            
            #line 20 "..\..\Views\Download\Index.cshtml"
, Tuple.Create(Tuple.Create("", 675), Tuple.Create<System.Object, System.Int32>(filesForMask.pathes[i]
            
            #line default
            #line hidden
, 675), false)
);

WriteLiteral(">Download</a>\r\n");

            
            #line 21 "..\..\Views\Download\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Download\Index.cshtml"
                 if (file.Contains(".pdf") || file.Contains(".txt") || file.Contains(".html") || file.Contains(".mp4"))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 876), Tuple.Create("\"", 945)
, Tuple.Create(Tuple.Create("", 883), Tuple.Create("/Download/downloadFile?nameFile=", 883), true)
            
            #line 23 "..\..\Views\Download\Index.cshtml"
, Tuple.Create(Tuple.Create("", 915), Tuple.Create<System.Object, System.Int32>(filesForMask.pathes[i]
            
            #line default
            #line hidden
, 915), false)
, Tuple.Create(Tuple.Create("", 938), Tuple.Create("&View=1", 938), true)
);

WriteLiteral(">View</a>\r\n");

            
            #line 24 "..\..\Views\Download\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <br>\r\n            </div>\r\n");

            
            #line 27 "..\..\Views\Download\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Download\Index.cshtml"
              i++; 
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Download\Index.cshtml"
                    
        }
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Download\Index.cshtml"
          i = 0;
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Download\Index.cshtml"
                 
    }
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">No files has been found</div>\r\n");

            
            #line 35 "..\..\Views\Download\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Download\Index.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
