#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Admin/Index.cshtml")]
    public partial class _Views_Admin_Index_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Admin.Models.AdminAddUserModel>
    {
        public _Views_Admin_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Admin\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h4>Index of Admin used only for links:</h4>\r\n\r\n");

            
            #line 8 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Add Role to sytem", "AddRole", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 9 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Remove Role from system", "RemoveRole", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 10 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Add user to specific role", "AddUser", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 11 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Remove Role from user", "RemoveUser", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 12 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Add Mask to system", "AddMask", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 13 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Remove Mask form system", "RemoveMask", "Admin"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n");

            
            #line 14 "..\..\Views\Admin\Index.cshtml"
Write(Html.ActionLink("Register", "Register", "Account"));

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n<br>\r\n\r\n");

            
            #line 17 "..\..\Views\Admin\Index.cshtml"
Write(Html.Partial("_Search"));

            
            #line default
            #line hidden
WriteLiteral("\r\nExisting roles: <br>\r\n<ul");

WriteLiteral(" id=\"myUL\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Views\Admin\Index.cshtml"
 foreach (var usersInRole in Model.UsersInRoles)
{

            
            #line default
            #line hidden
WriteLiteral("    <li>\r\n        <b><a");

WriteLiteral(" class=\"header\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Admin\Index.cshtml"
                        Write(usersInRole.role);

            
            #line default
            #line hidden
WriteLiteral("</a></b>\r\n");

            
            #line 24 "..\..\Views\Admin\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Admin\Index.cshtml"
         foreach (var user in usersInRole.Users)
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"ul-item\"");

WriteLiteral(">");

            
            #line 26 "..\..\Views\Admin\Index.cshtml"
                          Write(user);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 27 "..\..\Views\Admin\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </li>\r\n");

            
            #line 29 "..\..\Views\Admin\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</ul>");

        }
    }
}
#pragma warning restore 1591
