#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    #line 1 "..\..\Views\Alarm\Index.cshtml"
    using UsersDiosna.Handlers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Alarm/Index.cshtml")]
    public partial class _Views_Alarm_Index_cshtml : System.Web.Mvc.WebViewPage<List<AlarmHelper.alarm>>
    {
        public _Views_Alarm_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Alarm\Index.cshtml"
  
    ViewBag.Title = "Alarms";
    int pageLess = ViewBag.page - 1;
    int pageMore = ViewBag.page + 1;
    List<int> currentAlarmIDs = new List<int>();
    ViewBag.filtered = Session["filtered"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<h4>Alarms</h4>\r\n<div>\r\n");

            
            #line 14 "..\..\Views\Alarm\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Alarm\Index.cshtml"
     if (pageLess >= 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 367), Tuple.Create("\"", 396)
, Tuple.Create(Tuple.Create("", 374), Tuple.Create("/Alarm/Page/", 374), true)
            
            #line 16 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 386), Tuple.Create<System.Object, System.Int32>(pageLess
            
            #line default
            #line hidden
, 386), false)
, Tuple.Create(Tuple.Create("", 395), Tuple.Create("/", 395), true)
);

WriteLiteral(">&lArr;</a>\r\n");

            
            #line 17 "..\..\Views\Alarm\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    Page: ");

            
            #line 18 "..\..\Views\Alarm\Index.cshtml"
     Write(ViewBag.page);

            
            #line default
            #line hidden
WriteLiteral("\r\n    <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 475), Tuple.Create("\"", 504)
, Tuple.Create(Tuple.Create("", 482), Tuple.Create("/Alarm/Page/", 482), true)
            
            #line 19 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(pageMore
            
            #line default
            #line hidden
, 494), false)
, Tuple.Create(Tuple.Create("", 503), Tuple.Create("/", 503), true)
);

WriteLiteral(">&rArr;</a>\r\n");

            
            #line 20 "..\..\Views\Alarm\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Alarm\Index.cshtml"
     if (ViewBag.filtered != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\Alarm\Index.cshtml"
       Write(ViewBag.filtered);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <a");

WriteLiteral(" class=\"btn-sm btn-info\"");

WriteLiteral(" href=\"/Alarm/CancelFilter/\"");

WriteLiteral(">Cancel current filter on alarms</a>\r\n        </div>\r\n");

            
            #line 26 "..\..\Views\Alarm\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 27 "..\..\Views\Alarm\Index.cshtml"
     if (Session["AlarmDB"].ToString() != "")
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"btn-toolbar\"");

WriteLiteral(">\r\n        <br>\r\n        <p>\r\n        <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 897), Tuple.Create("\"", 992)
, Tuple.Create(Tuple.Create("", 904), Tuple.Create("/AlarmNotification/All?name=", 904), true)
            
            #line 32 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 932), Tuple.Create<System.Object, System.Int32>(Request.QueryString["name"]
            
            #line default
            #line hidden
, 932), false)
, Tuple.Create(Tuple.Create("", 960), Tuple.Create("&plc=", 960), true)
            
            #line 32 "..\..\Views\Alarm\Index.cshtml"
                          , Tuple.Create(Tuple.Create("", 965), Tuple.Create<System.Object, System.Int32>(Request.QueryString["plc"]
            
            #line default
            #line hidden
, 965), false)
);

WriteLiteral(">Notification from all alarms</a>\r\n        <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteLiteral(" href=\"/Alarm/FilterAll\"");

WriteLiteral(">Filter from all alarms</a>\r\n        <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteLiteral(" href=\"/Alarm/FilterCurrent\"");

WriteLiteral(">Filter from current alarms</a>\r\n        <a");

WriteLiteral(" class=\"btn-sm btn-primary\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1253), Tuple.Create("\"", 1356)
, Tuple.Create(Tuple.Create("", 1260), Tuple.Create("/AlarmNotification/FromCurrent?name=", 1260), true)
            
            #line 35 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1296), Tuple.Create<System.Object, System.Int32>(Request.QueryString["name"]
            
            #line default
            #line hidden
, 1296), false)
, Tuple.Create(Tuple.Create("", 1324), Tuple.Create("&plc=", 1324), true)
            
            #line 35 "..\..\Views\Alarm\Index.cshtml"
                                 , Tuple.Create(Tuple.Create("", 1329), Tuple.Create<System.Object, System.Int32>(Request.QueryString["plc"]
            
            #line default
            #line hidden
, 1329), false)
);

WriteLiteral(">Notification from current alarms</a>\r\n        </p>\r\n    </div>\r\n");

            
            #line 38 "..\..\Views\Alarm\Index.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"btn-toolbar\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"/Alarm/Filter\"");

WriteLiteral(">Filter from all alarms</a>\r\n            <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"/Alarm/Filter\"");

WriteLiteral(">Filter from current alarms</a>\r\n        </div>\r\n");

            
            #line 45 "..\..\Views\Alarm\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n<table");

WriteLiteral(" class=\"table table-striped table-bordered table-condensed table-hover\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>Id</th>\r\n        <th>Name of alarm</th>\r\n        <th>Ori" +
"gin</th>\r\n        <th>Expiry</th>\r\n    </tr>\r\n");

            
            #line 54 "..\..\Views\Alarm\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\Alarm\Index.cshtml"
     for (int i = 0; i < Model.Count; i++)
    {

            
            #line default
            #line hidden
WriteLiteral("        <tr>\r\n            <td>");

            
            #line 57 "..\..\Views\Alarm\Index.cshtml"
           Write(Model[i].id);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 58 "..\..\Views\Alarm\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Alarm\Index.cshtml"
             if (!currentAlarmIDs.Exists(p => p == Model[i].id)) {
                currentAlarmIDs.Add(Model[i].id);
            }

            
            #line default
            #line hidden
WriteLiteral("            <td>");

            
            #line 61 "..\..\Views\Alarm\Index.cshtml"
           Write(Model[i].title);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td");

WriteAttribute("id", Tuple.Create(" id=\"", 2181), Tuple.Create("\"", 2193)
, Tuple.Create(Tuple.Create("", 2186), Tuple.Create("date_", 2186), true)
            
            #line 62 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2191), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 2191), false)
);

WriteLiteral(">");

            
            #line 62 "..\..\Views\Alarm\Index.cshtml"
                        Write(Model[i].originTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            <td");

WriteAttribute("id", Tuple.Create(" id=\"", 2237), Tuple.Create("\"", 2252)
, Tuple.Create(Tuple.Create("", 2242), Tuple.Create("expDate_", 2242), true)
            
            #line 63 "..\..\Views\Alarm\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2250), Tuple.Create<System.Object, System.Int32>(i
            
            #line default
            #line hidden
, 2250), false)
);

WriteLiteral(">");

            
            #line 63 "..\..\Views\Alarm\Index.cshtml"
                           Write(Model[i].expiryTime);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        </tr>\r\n");

            
            #line 65 "..\..\Views\Alarm\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 66 "..\..\Views\Alarm\Index.cshtml"
      Session["alarmIDs"] = currentAlarmIDs;
            
            #line default
            #line hidden
WriteLiteral(@"
</table>
<script>
        function DateTime(date){
                var d = new Date(date);
                var offset = d.getTimezoneOffset();
                var offseted_miliseconds = d.getTime() - (offset*60000);
                var DateTime = new Date(offseted_miliseconds);
                var localDateTime = DateTime.toLocaleString();
                return localDateTime;
            }
</script>
");

            
            #line 78 "..\..\Views\Alarm\Index.cshtml"
 for (int i = 0; i < Model.Count; i++)
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n            var date = \"");

            
            #line 81 "..\..\Views\Alarm\Index.cshtml"
                   Write(Model[i].originTime);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            var expDate = \"");

            
            #line 82 "..\..\Views\Alarm\Index.cshtml"
                      Write(Model[i].expiryTime);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n            var localDateTime = DateTime(date);\r\n            document.getEl" +
"ementById(\"date_\" + \"");

            
            #line 85 "..\..\Views\Alarm\Index.cshtml"
                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("\").innerHTML = localDateTime;\r\n            var localExpDateTime = DateTime(expDat" +
"e);\r\n            document.getElementById(\"expDate_\" + \"");

            
            #line 87 "..\..\Views\Alarm\Index.cshtml"
                                             Write(i);

            
            #line default
            #line hidden
WriteLiteral("\").innerHTML = localExpDateTime;\r\n    </script>\r\n");

            
            #line 89 "..\..\Views\Alarm\Index.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
