#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Views\ReportOverview\Index.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 1 "..\..\Views\ReportOverview\Index.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ReportOverview/Index.cshtml")]
    public partial class _Views_ReportOverview_Index_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Report.Models.OverviewReportModel>
    {
        public _Views_ReportOverview_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\ReportOverview\Index.cshtml"
  
    ViewBag.Title = "Index";
    string name = string.Empty;
    int EndType = 0;
    int amntTotal = 0;
    int amntOverall = 0;
    int amnt = 0;
    bool colourRow;
    int count = 0;
    int countOverall = 0;
    int year = ViewBag.year;
    int monthLess = ViewBag.Month - 1;
    int monthMore = ViewBag.Month + 1;
    if (monthLess < 1)
    {
        year--;
        monthLess = 12;
    }
    if (monthMore > 12)
    {
        year++;
        monthMore = 1;
    }
    Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
    DateTime monthDT = new DateTime(year, ViewBag.month, 1);
    string monthName = monthDT.ToString("MMMM");


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Cunsumption Report</h2>\r\n\r\n<div");

WriteLiteral(" class=\" col-md-10\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 886), Tuple.Create("\"", 931)
, Tuple.Create(Tuple.Create("", 893), Tuple.Create("/ReportOverview/Month/", 893), true)
            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
, Tuple.Create(Tuple.Create("", 915), Tuple.Create<System.Object, System.Int32>(monthLess
            
            #line default
            #line hidden
, 915), false)
, Tuple.Create(Tuple.Create("", 925), Tuple.Create("/", 925), true)
            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
, Tuple.Create(Tuple.Create("", 926), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 926), false)
);

WriteLiteral(">-1 month</a> Month: ");

            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
                                                                                               Write(monthName);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
                                                                                                          Write(year);

            
            #line default
            #line hidden
WriteLiteral(" <a");

WriteLiteral(" class=\"btn-primary btn-xs\"");

WriteAttribute("href", Tuple.Create(" href=\"", 999), Tuple.Create("\"", 1044)
, Tuple.Create(Tuple.Create("", 1006), Tuple.Create("/ReportOverview/Month/", 1006), true)
            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
                                                                                               , Tuple.Create(Tuple.Create("", 1028), Tuple.Create<System.Object, System.Int32>(monthMore
            
            #line default
            #line hidden
, 1028), false)
, Tuple.Create(Tuple.Create("", 1038), Tuple.Create("/", 1038), true)
            
            #line 37 "..\..\Views\ReportOverview\Index.cshtml"
                                                                                                          , Tuple.Create(Tuple.Create("", 1039), Tuple.Create<System.Object, System.Int32>(year
            
            #line default
            #line hidden
, 1039), false)
);

WriteLiteral(">+1 month</a>\r\n    <p></p>\r\n</div>\r\n<table");

WriteLiteral(" class=\"table-bordered table-condensed table-hover\"");

WriteLiteral(">\r\n    <thead>\r\n        <tr>\r\n            <th>Day</th>\r\n");

            
            #line 44 "..\..\Views\ReportOverview\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\ReportOverview\Index.cshtml"
             if(Model.Data.Max(p=> p.MotherCultureBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Mother culture</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 47 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 48 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.FlourBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Flour</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 51 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 52 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.WaterBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Water</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 55 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 56 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.OldBreadBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Old Bread</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 59 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 60 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.LiquidYeastBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Liquid yeast</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 63 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 64 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.MixtureBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Mixture</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 67 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 68 "..\..\Views\ReportOverview\Index.cshtml"
             if (Model.Data.Max(p => p.GenericBatchCount > 0)) {

            
            #line default
            #line hidden
WriteLiteral("                <th>Generic component</th>\r\n");

WriteLiteral("                <td");

WriteLiteral(" class=\"th-Report\"");

WriteLiteral("></td>\r\n");

            
            #line 71 "..\..\Views\ReportOverview\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tr>\r\n    </thead>\r\n");

            
            #line 74 "..\..\Views\ReportOverview\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\ReportOverview\Index.cshtml"
     for (int day = 1; day <= DateTime.DaysInMonth(year, ViewBag.month); day++)
    {
        
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\ReportOverview\Index.cshtml"
           DateTime dayDT = new DateTime(year, ViewBag.month, day); string sDay = dayDT.DayOfWeek.ToString();  
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\ReportOverview\Index.cshtml"
                                                                                                                

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");

            
            #line 78 "..\..\Views\ReportOverview\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\ReportOverview\Index.cshtml"
                 if (dayDT.DayOfWeek == DayOfWeek.Saturday || dayDT.DayOfWeek == DayOfWeek.Sunday)
                {
                    colourRow = true;

            
            #line default
            #line hidden
WriteLiteral("                    <td");

WriteLiteral(" style=\"background-color: lightgoldenrodyellow\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\ReportOverview\Index.cshtml"
                                                                  Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 81 "..\..\Views\ReportOverview\Index.cshtml"
                                                                        Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 82 "..\..\Views\ReportOverview\Index.cshtml"
                }
                else
                {
                    colourRow = false;

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 86 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(day);

            
            #line default
            #line hidden
WriteLiteral(". ");

            
            #line 86 "..\..\Views\ReportOverview\Index.cshtml"
                         Write(sDay);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 87 "..\..\Views\ReportOverview\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 88 "..\..\Views\ReportOverview\Index.cshtml"
                 if (Model.Data.Where(p =>  >= day) {

            
            #line default
            #line hidden
WriteLiteral("                    <td>");

            
            #line 89 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day-1].MotherCultureAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 90 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].MotherCultureBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 91 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].FlourAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 92 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].FlourBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 93 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].WaterAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 94 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].WaterBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 95 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].OldBreadAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 96 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].OldBreadBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 97 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].LiquidYeastAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 98 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].LiquidYeastBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 99 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].MixtureAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 100 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].MixtureBatchCount);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 101 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].GenericAmnt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>");

            
            #line 102 "..\..\Views\ReportOverview\Index.cshtml"
                   Write(Model.Data[day - 1].GenericBatchCount);

            
            #line default
            #line hidden
WriteLiteral(@"</td>
                }
                else
                {
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                }
            </tr>
");

            
            #line 115 "..\..\Views\ReportOverview\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>");

        }
    }
}
#pragma warning restore 1591
