#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NewSchemes/Index.cshtml")]
    public partial class _Views_NewSchemes_Index_cshtml : System.Web.Mvc.WebViewPage<UsersDiosna.Sheme.Models.SchemeEditor>
    {
        public _Views_NewSchemes_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\NewSchemes\Index.cshtml"
  
    ViewBag.Title = "Scheme Editor";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>New scheme</h2>\r\n<!--<script src=\"~/Scripts/NewSchemes.js\" ></script>-->\r" +
"\n<div>\r\n    ");

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\NewSchemes\Index.cshtml"
Write(Html.Raw(ViewBag.SvgXml));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");

WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
