#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UsersDiosna;
    using UsersDiosna.Controllers;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 6 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - Users Diosna</title>\r\n");

WriteLiteral("    ");

            
            #line 7 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n");

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
  
    ViewBag.error = Session["tempforview"];
    ViewBag.success = Session["success"];

            
            #line default
            #line hidden
WriteLiteral("\r\n<body");

WriteLiteral(" onresize=\"responsive()\"");

WriteLiteral(" onload=\"notification()\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" id=\"bell\"");

WriteLiteral(">Notifications <span");

WriteLiteral(" class=\"glyphicon glyphicon-bell\"");

WriteLiteral("></span></a>\r\n                        <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(" id=\"notification\"");

WriteLiteral(">\r\n                            <li><a");

WriteLiteral(" href=\"/Notification/\"");

WriteLiteral("><b>Notifications center</b></a></li>\r\n                            ");

WriteLiteral("\r\n                        </ul>\r\n                    </li>\r\n                </ul>" +
"\r\n");

            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
                 if (Session["types"] != null && ViewBag.menuDisable != true)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" onclick=\"menuShow()\"");

WriteLiteral(" style=\"cursor: pointer; cursor: hand;\"");

WriteLiteral("><a");

WriteLiteral(" id=\"menuShow\"");

WriteLiteral("></a></li>\r\n                        <li");

WriteLiteral(" onclick=\"menuHide()\"");

WriteLiteral(" style=\"cursor: pointer; cursor: hand;\"");

WriteLiteral("><a");

WriteLiteral(" id=\"menuHide\"");

WriteLiteral(">Hide Menu</a></li>\r\n                    </ul>\r\n");

            
            #line 42 "..\..\Views\Shared\_Layout.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                ");

            
            #line 43 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
     if (Session["types"] != null && ViewBag.menuDisable != true)
    {

            
            #line default
            #line hidden
WriteLiteral(@"        <script>
            function menuHide() {
                $('#menuShow').text(""Show menu"");
                $('#menuHide').text("""");
                $('.sidenav').hide();
            }
            function menuShow() {
                $('#menuHide').text(""Hide menu"");
                $('#menuShow').text("""");
                $('.sidenav').show();
            }
        </script>
");

WriteLiteral("        <div");

WriteLiteral(" class=\"sidenav\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Partial("~/Views/Menu/_Menu.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(" id=\"container-body\"");

WriteLiteral(@">
        <script>
            var sidenavWidth = $('.sidenav').width();
            document.getElementById('container-body').style.marginLeft = sidenavWidth + 'px';
            function responsive() {
                var sidenavWidth = $('.sidenav').width();
                document.getElementById('container-body').style.marginLeft = sidenavWidth + 'px';
            }
        </script>
");

            
            #line 74 "..\..\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Shared\_Layout.cshtml"
         if (ViewBag.error != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
                                   Write(ViewBag.error);

            
            #line default
            #line hidden
WriteLiteral("<br></div>\r\n");

            
            #line 77 "..\..\Views\Shared\_Layout.cshtml"
            Session["tempforview"] = null;
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 79 "..\..\Views\Shared\_Layout.cshtml"
         if (ViewBag.message != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\Shared\_Layout.cshtml"
                                   Write(ViewBag.message);

            
            #line default
            #line hidden
WriteLiteral("<br></div>\r\n");

            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"
            ViewBag.message = null;
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 84 "..\..\Views\Shared\_Layout.cshtml"
         if (ViewBag.warning != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
                                    Write(ViewBag.warning);

            
            #line default
            #line hidden
WriteLiteral("<br></div>\r\n");

            
            #line 87 "..\..\Views\Shared\_Layout.cshtml"
            ViewBag.warning = null;
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 89 "..\..\Views\Shared\_Layout.cshtml"
         if (ViewBag.success != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(">");

            
            #line 91 "..\..\Views\Shared\_Layout.cshtml"
                                        Write(ViewBag.success);

            
            #line default
            #line hidden
WriteLiteral("<br></div>\r\n");

            
            #line 92 "..\..\Views\Shared\_Layout.cshtml"
            Session["success"] = null;
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 94 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <hr />\r\n");

            
            #line 97 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 97 "..\..\Views\Shared\_Layout.cshtml"
      
        Session["tempforview"] = null;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n    <footer>\r\n        <p>&copy; ");

            
            #line 101 "..\..\Views\Shared\_Layout.cshtml"
             Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - DIOSNA CS s.r.o. - Liberec</p>\r\n    </footer>\r\n");

WriteLiteral("    ");

            
            #line 103 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/filter"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 104 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 105 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 106 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 107 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/notification"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 108 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
